// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Jy66enGWmhLRG6I1dMeu26zCjiZva44',
    appId: '1:971862194159:web:8bea7672ea1ad7cd0a281a',
    messagingSenderId: '971862194159',
    projectId: 'blooddonation-b459d',
    authDomain: 'blooddonation-b459d.firebaseapp.com',
    storageBucket: 'blooddonation-b459d.firebasestorage.app',
    measurementId: 'G-3ZKVYFDGTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7Y-pMsVNg-mdVfHhPUvUV8_3fftqvpE',
    appId: '1:971862194159:android:b8a79079607ad5bc0a281a',
    messagingSenderId: '971862194159',
    projectId: 'blooddonation-b459d',
    storageBucket: 'blooddonation-b459d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjD3M_Zd8ZvMNK19ZrdtgkDb09LhZtmK8',
    appId: '1:971862194159:ios:721a131a21ec0dd90a281a',
    messagingSenderId: '971862194159',
    projectId: 'blooddonation-b459d',
    storageBucket: 'blooddonation-b459d.firebasestorage.app',
    iosBundleId: 'com.example.blooddonation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjD3M_Zd8ZvMNK19ZrdtgkDb09LhZtmK8',
    appId: '1:971862194159:ios:721a131a21ec0dd90a281a',
    messagingSenderId: '971862194159',
    projectId: 'blooddonation-b459d',
    storageBucket: 'blooddonation-b459d.firebasestorage.app',
    iosBundleId: 'com.example.blooddonation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6Jy66enGWmhLRG6I1dMeu26zCjiZva44',
    appId: '1:971862194159:web:a59b734def4193f40a281a',
    messagingSenderId: '971862194159',
    projectId: 'blooddonation-b459d',
    authDomain: 'blooddonation-b459d.firebaseapp.com',
    storageBucket: 'blooddonation-b459d.firebasestorage.app',
    measurementId: 'G-821DECNKZX',
  );
}
